### ISSUE TITLE
Release improvements -  wrong "Latest release" on github + kind request for a .deb package

### ISSUE THREAD

**Issue by nifr** [sharkdp/content_inspector#4]
Hey @sharkdp,

1.) 
I discovered that right now there are 4 releases for this lib (the latest being `v0.24`) but the "Latest release" on github is still shown as `v0.22` for me. See [/releases](https://github.com/sharkdp/content_inspector/releases).

2.)
Could you add a `*.deb` to the releases as you've done for your other tools? 
That'd make installation with provisioning tools (`ansible`, `chef`, ... etc) a breeze. 

I'm looking to provision `content_inspector` to my systems and use it with the `--preview` flag of `fzf` to speed up checking for binary files.

Thanks for all the work you put into these helpers. Greatly appreciated!

**Comment by sharkdp** [comment]
> 1.)
> I discovered that right now there are 4 releases for this lib (the latest being `v0.24`) but the "Latest release" on github is still shown as `v0.22` for me. See [/releases](https://github.com/sharkdp/content_inspector/releases).

Since this is "just" a library without any build artifacts, I didn't care too much about the releases on GitHub. The import thing here are the releases on crates.io. But it's fixed now. I released v0.2.3 and v0.2.4.

> 2.)
> Could you add a `*.deb` to the releases as you've done for your other tools?
> That'd make installation with provisioning tools (`ansible`, `chef`, ... etc) a breeze.

Hm.. I guess you are interested in the `inspect` demo tool that comes with the library? It was never really intended as a real standalone tool, but more like a showcase of what could be done with the library.

Or are you interested in a package for the library itself? I'm not sure if that would be very helpful, given that most Rust applications statically link other crates.

**Comment by sharkdp** [comment]
> I'm looking to provision `content_inspector` to my systems and use it with the `--preview` flag of `fzf` to speed up checking for binary files.

What kind of preview are you specifically interested in? If you want to display the file contents and have problems with binary files, you could potentially try my `bat` tool (https://github.com/sharkdp/bat) which uses `content_inspector` internally in order to detect binary files (and not dump them to the terminal).

See also: https://github.com/sharkdp/bat/issues/448#issuecomment-466882258

**Comment by nifr** [comment]
Hey David,
thanks for the super quick reply :smile:  

I was indeed looking for the `inspect` demo tool to speed up the detection of binary files. I'm using `bat`  for the file-preview itself but didn't know that `bat` already uses this lib internally . The [example](https://github.com/junegunn/fzf#preview-window) in the `fzf` repository looks like this:

    fzf --preview '[[ $(file --mime {}) =~ binary ]] &&
                 echo {} is a binary file ||
                 (bat --style=numbers --color=always {} ||
                  highlight -O ansi -l {} ||
                  coderay {} ||
                  rougify {} ||
                  cat {}) 2> /dev/null | head -500'

That's why I thought I could speed up the `file --mime` part in there by replacing it with `inspect`. 

Now I realized `bat` already outputs ...

     File: files/wallpaper.png   <BINARY>

... so the binary check only makes sense in case of the fallback to `cat` which would dump the binary. 
I don't need any fallback at all because `bat` is always available. That's a great find and simplifies my configuration. Cool :sunglasses: 
 
Thanks for the clarification!  

I'm closing this issue - keep up the good work David, hats off and big respect from me!

**Comment by sharkdp** [comment]
Great to hear, thank you for the summary!
